Repository Arsh-ak7/Algo, pull requests merged in 2020-10, with the labels that each got.

#1 Added QuickSort
  QuickSort.js
Labels: hacktoberfest

#2 Add files via upload
  Addition.cpp
  Life.c
Labels: hacktoberfest-accepted

#3 Create closestpair.cpp
  closestpair.cpp
Labels: hacktoberfest, hacktoberfest-accepted
